# Generated by Django 4.1.7 on 2023-03-14 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0007_alter_service_chief'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('available', models.BooleanField(default=True, verbose_name='available')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='LabComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('low', models.CharField(max_length=5)),
                ('high', models.CharField(max_length=5)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.lab')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('abstract', models.TextField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=20)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.labcomponent')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.record')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.TextField()),
                ('status', models.TextField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.record')),
            ],
        ),
        migrations.CreateModel(
            name='PlanOfCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.TextField()),
                ('planned_date', models.DateField()),
                ('instructions', models.TextField()),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.record')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('dose', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='prescription guidelines')),
                ('duration', models.CharField(blank=True, max_length=57, null=True, verbose_name='duration')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.medicine')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.record')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('conclusion', models.TextField()),
                ('result', models.FileField(blank=True, null=True, upload_to='test_result/')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.record')),
            ],
        ),
        migrations.CreateModel(
            name='Allergie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('reaction', models.CharField(max_length=200)),
                ('severity', models.CharField(max_length=200)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.record')),
            ],
        ),
    ]
