# Generated by Django 4.1.7 on 2023-03-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labcomponent',
            name='unit',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='labcomponent',
            name='high',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='labcomponent',
            name='low',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='record',
            name='abstract',
            field=models.TextField(blank=True, null=True),
        ),
    ]
