version: "3.8"

services:
  ipfs:
    build: 
      context: ./ipfs
    image: healtech_ipfs:latest
    container_name: ipfs-node
    ports:
      - "5001:5001"
      - "4001:4001"
  backend:
    build:
      context: ./backend-Django
    image: healtech_backend:v0.1
    volumes:
      - type: bind
        source: ./backend-Django/src
        target: /home/healtech-backend/src
    ports:
      - 8000:8000
    container_name: backend-app
  frontend:
    build:
      context: ./frontend-Vue
    image: healtech_frontend:v0.1
    volumes:
      - type: bind
        source: ./frontend-Vue/src
        target: /home/healtech-frontend/src
    ports:
      - 8080:8080
    container_name: frontend-app
    depends_on:
      - backend
      - ipfs