version: "3.8"

services:
  backend:
    build:
      context: ./backend-Django
      target: healtech_backend
    volumes:
      - type: bind
        source: ./backend-Django/src
        target: /home/healtech-backend/src
    ports:
      - 8000:8000
    container_name: backend-app
  frontend:
    build:
      context: ./frontend-Vue
      target: healtech_frontend
    volumes:
      - type: bind
        source: ./frontend-Vue/src
        target: /home/healtech-frontend/src
    ports:
      - 8080:8080
    container_name: frontend-app
    depends_on:
      - backend