# Generated by Django 4.1.7 on 2023-03-06 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default=datetime.time(14, 54, 49, 373825), verbose_name='appointment time'),
        ),
    ]
