# Generated by Django 4.1.7 on 2023-03-08 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0002_alter_appointment_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="time",
            field=models.TimeField(
                default=datetime.time(11, 45, 17, 412217),
                verbose_name="appointment time",
            ),
        ),
    ]
