<<<<<<< HEAD
# Generated by Django 4.1.7 on 2023-03-08 22:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0003_alter_appointment_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="time",
            field=models.TimeField(
                default=datetime.time(23, 46, 8, 840118),
                verbose_name="appointment time",
            ),
        ),
    ]
=======
# Generated by Django 4.1.7 on 2023-03-14 21:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default=datetime.time(22, 4, 49, 940452), verbose_name='appointment time'),
        ),
    ]
>>>>>>> 5b625857de24bae79b2fe52b7e8d3e166df93f8c
