# Generated by Django 4.1.7 on 2023-03-14 21:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default=datetime.time(22, 4, 49, 940452), verbose_name='appointment time'),
        ),
    ]
