# Generated by Django 4.1.7 on 2023-03-20 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_alter_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default=datetime.time(13, 46, 51, 37127), verbose_name='appointment time'),
        ),
    ]
