# Generated by Django 4.1.7 on 2023-03-01 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_admin_phone_alter_admin_profile_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='phone',
            field=models.CharField(blank=True, max_length=27, null=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=models.CharField(blank=True, max_length=27, null=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=27, null=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=27, null=True, verbose_name='phone number'),
        ),
    ]
