# Generated by Django 4.1.7 on 2023-03-06 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='chief',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.doctor'),
        ),
    ]
