# Generated by Django 4.1.7 on 2023-03-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_service_chief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='gender',
            field=models.CharField(choices=[('Male', 'Masculin'), ('Female', 'Feminin')], default='Male', max_length=20, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('Male', 'Masculin'), ('Female', 'Feminin')], default='Male', max_length=20, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('Male', 'Masculin'), ('Female', 'Feminin')], default='Male', max_length=20, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Masculin'), ('Female', 'Feminin')], default='Male', max_length=20, verbose_name='gender'),
        ),
    ]
