# Generated by Django 4.1.7 on 2023-05-10 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_admin_gender_alter_doctor_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='bc_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(choices=[('Married', 'Marié'), ('Widowed', 'Veuf'), ('Separated', 'Séparé'), ('Divorced', 'Divorce'), ('Single', 'Célibataire')], default='Single', max_length=20, verbose_name='marital status'),
        ),
    ]
